texto1 = input("Digite o texto 1: ")
texto2 = input("Digite o texto 2: ")
print(f"O texto 1 tem {len(texto1)} caracteres")
print(f"O texto 2 tem {len(texto2)} caracteres")
print(f"As Strings possuem a mesma quantidade de caracteres? {len(texto1) == len(texto2)}")
print(f"As strings são iguais? {texto1 == texto2}")